feat: support localization
TheTNB/panel pull request #91
Opened 2024-04-22 12:16 UTC by kkumar-gcc

2024-04-22 13:15 UTC, devhaozi requested changes

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/monitoring.go
> +	return facades.Lang(ctx).Get("panel:monitoring.description")
suggest use: `panel:command.monitoring.description`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +	return facades.Lang(ctx).Get("panel.description")
suggest use: `panel:command.panel.description`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Greenln(translate.Get("panel.getPort.port") + ": " + port)
suggest use: `panel:command.panel.getPort`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Greenln(translate.Get("panel.getEntrance.entrance") + ": " + facades.Config().GetString("http.entrance"))
suggest use: `panel:command.panel.getEntrance`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Yellowln(facades.Config().GetString("panel.name") + " - " + translate.Get("panel.cmd_tool") + " - " + facades.Config().GetString("panel.version"))
suggest use: `panel:command.panel.tool`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Greenln(translate.Get("panel.use_commands") + "：")
suggest use: `panel:command.panel.use`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Greenln("panel update " + translate.Get("panel.update.description"))
suggest use: `panel:command.panel.update`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Greenln("panel getInfo " + translate.Get("panel.getInfo.description"))
suggest use: `panel:command.panel.getInfo`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Greenln("panel getPort " + translate.Get("panel.getPort.description"))
suggest use: `panel:command.panel.getPort`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Greenln("panel getEntrance " + translate.Get("panel.getEntrance.description"))
suggest use: `panel:command.panel.getEntrance`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Greenln("panel deleteEntrance " + translate.Get("panel.deleteEntrance.description"))
suggest use: `panel:command.panel.deleteEntrance`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Greenln("panel cleanTask " + translate.Get("panel.cleanTask.description"))
suggest use: `panel:command.panel.cleanTask`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Greenln("panel backup {website/mysql/postgresql} {name} {path} {save_copies} " + translate.Get("panel.backup.description"))
suggest use: `panel:command.panel.backup`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Greenln("panel cutoff {website_name} {save_copies} " + translate.Get("panel.cutoff.description"))
suggest use: `panel:command.panel.cutoff`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Greenln("panel installPlugin {slug} " + translate.Get("panel.installPlugin.description"))
suggest use: `panel:command.panel.installPlugin`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Greenln("panel removeSite {name} " + translate.Get("panel.removeSite.description"))
suggest use: `panel:command.panel.removeSite`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Yellowln("panel writeMysqlPassword {password} " + translate.Get("panel.writeMysqlPassword.description"))
suggest use: `panel:command.panel.writeMysqlPassword`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Yellowln("panel writeSite {name} {status} {path} {php} {ssl} " + translate.Get("panel.writeSite.description"))
suggest use: `panel:command.panel.writeSite`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Yellowln("panel deleteSite {name} " + translate.Get("panel.deleteSite.description"))
suggest use: `panel:command.panel.deleteSite`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Yellowln("panel getSetting {name} " + translate.Get("panel.getSetting.description"))
suggest use: `panel:command.panel.getSetting`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Yellowln("panel writeSetting {name} {value} " + translate.Get("panel.writeSetting.description"))
suggest use: `panel:command.panel.writeSetting`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel.go
> +		color.Yellowln("panel deleteSetting {name} " + translate.Get("panel.deleteSetting.description"))
suggest use: `panel:command.panel.deleteSetting`

2024-04-22 13:15 UTC, devhaozi commented on app/console/commands/panel_task.go
> +	return facades.Lang(context.Background()).Get("panel:task.description")
suggest use: `panel:command.task.description`

2024-04-22 13:15 UTC, devhaozi commented on lang/zh_CN.json
Sync with above

2024-04-22 13:15 UTC, devhaozi commented on lang/en.json
Sync with above

2024-04-22 14:33 UTC, kkumar-gcc commented
Translation are organized as 
```json
"commands": {
   "command:signature": {
     ...
     "sub_command:signature": {...}
   }
}
```

2024-04-22 15:07 UTC, devhaozi approved these changes
LGTM

2024-04-28 13:10 UTC, devhaozi approved these changes
LGTM

2024-04-28 13:15 UTC, merged